#!/usr/bin/env bash
# install nginx server, configure it to port 80, set the redirect_me page, 404 not found page and the X-served-By header

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www


#echo "Hello World!" | sudo tee /var/www/html/index.html
#echo "Ceci n'est pas une page" > 404.html
#sudo mv 404.html /var/www/html
#echo "server {
#        listen 80 default_server;
#        listen [::]:80 default_server;
#        add_header X-Served-By $HOSTNAME;
#        root /var/www/html;
#        index index.html;
#        location /redirect_me {
#                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
#       }
#        error_page 404 /404.html;
#        location = /404.html{
#        internal;
#       }
#}" > default

#sudo mv -f default /etc/nginx/sites-available/default

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

# Create a firts index.html page
echo "Hello World!" > /var/www/html/index.html

# Add to the nginx configuration file a redirection to another page
FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
    sed -i "42i $STRING" /etc/nginx/sites-available/default
fi

# Add to the nginx configuration file a error page 404
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi
sudo service nginx restart
