#!/usr/bin/env bash
# install nginx server, configure it to port 80, set the redirect_me page, 404 not found page and the X-served-By header

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

echo 'Hello World!' |sudo tee  /var/www/html/index.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart

#echo "Hello World!" > /var/www/html/index.nginx-debian.html
#sudo mkdir /var/www/error
#echo "Ceci n'est pas une page" > /var/www/error/404.html
#echo "server {
#    listen 80 default_server;
#    listen [::]:80 default_server;
#    add_header X-Served-By $HOSTNAME;
#    root   /var/www/html;
#    index  index.html index.htm index.nginx-debian.html;
#    
#    server_name _;
#    
#    location /redirect_me {
#        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
#    }
#    error_page 404 /404.html;
#    location /404 {
#      root /var/www/error;
#     internal;
#    }
#}" > /etc/nginx/sites-available/default
#service nginx restart
