#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

sudo apt-get -y update
sudo apt-get install -y haproxy
config=\
"
frontend  web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 54904-web-01 54.157.144.57:80 check
        server 54904-web-02 3.85.148.165:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
