#!/usr/bin/env bash
# Configure a web server to run Nginx as an  nginx user listening on port 8080.

# set the  user in the config by replacing  '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# change ownership permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# An apache server can interfere with nginx so kill the process if it is running
pkill apache2
#start nginx services
sudo -u nginx service nginx start
