#!/usr/bin/env bash

ssh ubuntu@52.3.245.130
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDmj9kTTS8XavGT3vMfwmnUDYqkgDLkVJaqenXY2jTxEGPb7ip/uijUJ8xr9HmWfrv+O9NpJb4dEO0wfv0zcCIIrtac17JQKOgWHznMLDAgW8HaN7CiqA/vi4NNN5ZVXM6NAf5De3MdqGbiN4y5PWs0tRbpld56h/YfkvnV1yER1K/B66NAkKjLtpUNGP3eJZBV+Y3iFaul3x1vfHCVutDPOFOicupJLgAAs7illGBTjtmyTpoOnX2F1/pgHyucklSALjta0I84OfQoSMab8WLtGPiEh0lWNb594MEEJZLrrbMOYfJpPpNIp71JWG5a7M2vAYKmwcdOKwUy1nxftF0JNV3bJLVXkZLOW/jHDb+YB1yrVx/P9UXBvk1ZEr253fW8uCy06//RLZkZocPbyqJun/YyOQ8shzhSo5mJNjxikTd8nICAOcGrzDNZ+WJqGhGN88NzC37LZvQzFE3NYqFcbP5aFOOaUB7cGiiw8QLxdrie/XEQ4EEHK6p2ismitSM= root@d90c6837ab69 >> ~/.ssh/authorized_keys

